apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: orchestrator
data:
  GIT_SYNC_USERNAME: bGV2eXZpeA==
  GITSYNC_USERNAME: bGV2eXZpeA==
  GIT_SYNC_PASSWORD: UzZvdDUkQFAzaEhucmRHTjVvWGJFVCRWU1pDOXA1SHY3WVFjWHZMNHcyU0JFS2hMKnNtV0cyRGliQGlMNjdZSmdHRyVRRDhL
  GITSYNC_PASSWORD: UzZvdDUkQFAzaEhucmRHTjVvWGJFVCRWU1pDOXA1SHY3WVFjWHZMNHcyU0JFS2hMKnNtV0cyRGliQGlMNjdZSmdHRyVRRDhL
